name: "\U0001F680 Support new Wallet"
description: Request support to a new wallet
labels: ['enhancement']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this support request!
        We're thrilled to have another wallet supporting TRON.
  - type: input
    id: wallet-name
    attributes:
      label: Describe the name of wallet
      placeholder: Wallet name
    validations:
      required: true
  - type: input
    id: website
    attributes:
      label: Wallet website
      description: Please input the official website of the wallet.
      placeholder: The url of website
    validations:
      required: true
  - type: checkboxes
    id: platforms
    attributes:
      label: Supported platforms
      description: Describe platforms supported by the wallet.
      options:
        - label: Android
        - label: IOS
        - label: Chrome Extension
    validations:
      required: true
  - type: dropdown
    id: listed
    attributes:
      label: "Is the wallet listed on TRON Wallets"
      description: Please [contact the TRON team](mailto:application@tron.network) for wallet listing on [TRON Wallets](https://tron.network/wallet) and boost its visibility.
      options:
        - Not yet
        - Listed
      default: 1
